# Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: API MicroGateway
site_description: Cloud Native API Gateway
site_author: WSO2
site_url: http://foo.io/en/next/

# Repository
repo_name: microgateway
repo_url: https://github.com/wso2/product-microgateway
edit_uri: https://github.com/wso2/product-microgateway/www/edit/master/en/docs/

# Copyright
copyright: API Microgateway - Documentation

# Configuration
theme:
  name: material
  logo: images/logo.svg
  favicon: images/favicon.png
  palette:
    primary: indigo
    accent: indigo
  custom_dir: theme/material
  feature:
    tabs: true
  language: 'en'

# Customization
extra_css:
  - assets/css/theme.css
extra_javascript:
  - assets/lib/highlightjs/highlight.min.js
  - assets/js/theme.js
  - assets/lib/backtotop/js/util.js
  - assets/lib/backtotop/js/main.js
extra:
  social:
    - type: github
      link: https://github.com/wso2/product-microgateway
    - type: medium
    - type: twitter
      link: https://twitter.com/wso2apimanager
    - type: linkedin
      link:
  site_version: v3.1

# Google Analytics
google_analytics:
  - UA-103065-28
  - auto


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: false
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.attr_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - About:
    - About: docs/about-wso2-api-microgateway.md
