# Services for adapter, router and enforcer

apiVersion: v1
kind: Service
metadata:
  labels:
    app: adapter
  name: adapter-service
spec:
  type: NodePort
  selector:
    app: adapter
  ports:
    - name: "18000"
      port: 18000
      targetPort: 18000
      protocol: TCP
    - name: "9843"
      port: 9843
      targetPort: 9843
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: enforcer
  name: enforcer-service
spec:
  type: ClusterIP
  selector:
    app: enforcer
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: router
  name: router-service
spec:
  type: NodePort
  selector:
    app: router
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: "9095"
      port: 9095
      targetPort: 9095
      protocol: TCP