# Deployments for Adapter, router and enforcer

apiVersion: apps/v1
kind: Deployment
metadata:
  name: adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adapter
  template:
    metadata:
      labels:
        app: adapter
    spec:
      containers:
        - name: adapter
          volumeMounts:
            - mountPath: /home/wso2/security
              name: adapter-security-vol
            - mountPath: /home/wso2/conf
              name: adapter-conf-vol
          image: wso2/mg-adapter:4.0.0-m1
          ports:
            - containerPort: 18000
            - containerPort: 9843
      volumes:
        - name: adapter-security-vol
          configMap:
            name: adapter-security
        - name: adapter-conf-vol
          configMap:
            name: conf
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enforcer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enforcer
  template:
    metadata:
      labels:
        app: enforcer
    spec:
      containers:
        - name: enforcer
          volumeMounts:
            - mountPath: /home/wso2/mg/security
              name: enforcer-security-conf
            - mountPath: /home/wso2/conf
              name: enforcer-conf-vol
          image: wso2/mg-enforcer:4.0.0-m1
          ports:
            - containerPort: 8081
      volumes:
        - name: enforcer-security-conf
          secret:
            secretName: enforcer-security
            items:
              - key: client-truststore.jks
                path: client-truststore.jks
        - name: enforcer-conf-vol
          configMap:
            name: conf
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
        - name: router
          volumeMounts:
            - mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
              name: router-config
          image: wso2/mg-router:4.0.0-m1
          ports:
            - containerPort: 9000
            - containerPort: 9095
      volumes:
        - name: router-config
          configMap:
            name: router-cm
      restartPolicy: Always
